CREATE TABLE COMPANY
(
COMPANYID INT IDENTITY(1000,1) CONSTRAINT PK_COMPANYID PRIMARY KEY,
COMPANYNAME VARCHAR(100) CONSTRAINT U_COMPANYNAME UNIQUE,
WEBSITE VARCHAR(100),
EMAIL VARCHAR(100)
)

CREATE TABLE DEPARTMENT
(
DEPTID INT IDENTITY(1,1) CONSTRAINT PK_DEPTID PRIMARY KEY,
DEPTNAME VARCHAR(100) CONSTRAINT U_DEPTNAME UNIQUE,
DEPTLOCATION VARCHAR(100)
)

CREATE TABLE DESIGNATION
(
DESGID INT CONSTRAINT PK_DESGID PRIMARY KEY,
DESGNAME VARCHAR(100) CONSTRAINT U_DESGNAME UNIQUE,
CREATEDATE DATETIME CONSTRAINT D_CDATE DEFAULT GETDATE()
)

CREATE TABLE EMPLOYEE
(
EMPLID INT IDENTITY(1,1) CONSTRAINT PK_EMPLID PRIMARY KEY,
EMPLNAME VARCHAR(100) CONSTRAINT U_EMPLNAME UNIQUE,
DEPTID INT CONSTRAINT FK_DEPTID FOREIGN KEY REFERENCES DEPARTMENT(DEPTID),
DESGID INT CONSTRAINT FK_DESGID FOREIGN KEY REFERENCES DESIGNATION(DESGID),
BASICSALARY FLOAT,
INCENTIVE FLOAT,
BONUS FLOAT,
DOB DATETIME,
DOJ DATETIME CONSTRAINT D_DOJ DEFAULT GETDATE(),
GENDER VARCHAR(10),
EMAIL VARCHAR(100),
MOBILE VARCHAR(25),
CREATEDATE DATETIME CONSTRAINT D_CTDATE DEFAULT GETDATE(),
COMPANYID INT CONSTRAINT FK_COMPANYID FOREIGN KEY REFERENCES COMPANY(COMPANYID)
)

SELECT * FROM COMPANY

INSERT INTO COMPANY VALUES ('RHCONSULTANT','WWW.RHCONSULTANT.COM','RHCONSULTANT@GMAIL.COM')
INSERT INTO COMPANY VALUES ('RHINFRATECH','WWW.RHINFRATECH.COM','RHINRFATECH@GMAIL.COM')

SELECT * FROM DEPARTMENT

INSERT INTO DEPARTMENT VALUES ('FINANCE','DELHI')
INSERT INTO DEPARTMENT VALUES ('HR','DELHI')
INSERT INTO DEPARTMENT VALUES ('OPERATIONS','PUNE')
INSERT INTO DEPARTMENT VALUES ('ADMIN','PUNE')
INSERT INTO DEPARTMENT VALUES ('QUALITY','DELHI')

SELECT * FROM DESIGNATION

INSERT INTO DESIGNATION (DESGID,DESGNAME) VALUES (2,'MANAGER')
INSERT INTO DESIGNATION (DESGID,DESGNAME) VALUES (3,'SUPERVISOR')
INSERT INTO DESIGNATION (DESGID,DESGNAME) VALUES (4,'ASSOCIATE')
INSERT INTO DESIGNATION (DESGID,DESGNAME) VALUES (1,'HOD')

SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE (EMPLNAME,DEPTID,DESGID,BASICSALARY,INCENTIVE,BONUS,DOB,GENDER,EMAIL,MOBILE,COMPANYID)
VALUES ('KAPIL',1,2,25000,5000,10000,'10/10/1976','MALE','KAPIL@GMAIL.COM','4546687879',1000)
INSERT INTO EMPLOYEE (EMPLNAME,DEPTID,DESGID,BASICSALARY,INCENTIVE,BONUS,DOB,GENDER,EMAIL,MOBILE,COMPANYID)
VALUES ('SACHIN',2,1,50000,10000,100000,'12/08/1974','MALE','SACHIN@GMAIL.COM','4678643135',1000)
INSERT INTO EMPLOYEE (EMPLNAME,DEPTID,DESGID,BASICSALARY,INCENTIVE,BONUS,DOB,GENDER,EMAIL,MOBILE,COMPANYID)
VALUES ('AMIT',3,3,15000,2500,10000,'01/01/1980','MALE','AMIT@GMAIL.COM','546654667867',1001)
INSERT INTO EMPLOYEE (EMPLNAME,DEPTID,DESGID,BASICSALARY,INCENTIVE,BONUS,DOB,GENDER,EMAIL,MOBILE,COMPANYID)
VALUES ('GEETA',2,4,17000,2500,7500,'4/14/1976','FEMALE','GEETA@GMAIL.COM','457875343515',1000)
INSERT INTO EMPLOYEE (EMPLNAME,DEPTID,DESGID,BASICSALARY,INCENTIVE,BONUS,DOB,GENDER,EMAIL,MOBILE,COMPANYID)
VALUES ('DEEPAK',4,4,12000,2500,5000,'06/27/1985','MALE','DEEPAK@GMAIL.COM','78789321354',1001)
INSERT INTO EMPLOYEE (EMPLNAME,DEPTID,DESGID,BASICSALARY,INCENTIVE,BONUS,DOB,GENDER,EMAIL,MOBILE,COMPANYID)
VALUES ('RAJESH',5,2,32000,7500,10000,'03/21/1983','MALE','RAJESH@GMAIL.COM','78651132153',1001)

